config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :customers do 
  	resources :reservations
  end	

  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :reservations, dependent: :destroy		
  validates :name, presence: true,
                    length: { minimum: 2 }

end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :customer
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
	def index
		@customers = Customer.all
	end


	def show 
		@customer = Customer.find(params[:id])
	end	

	def new 
		@customer = Customer.new
	end

	def edit
		@customer = Customer.find(params[:id])
	end

	def create
  		
  		@customer = Customer.new(customer_params)
 
		if @customer.save
		    redirect_to @customer
	    else
		    render 'new'
   	    end
	end	

	def update
		@customer = Customer.find(params[:id])
 
  		if @customer.update(customer_params)
    		redirect_to @customer
  		else
    		render 'edit'
  		end

	end	

	def destroy 
	    @customer = Customer.find(params[:id])
  		@customer.destroy
 
        redirect_to customers_path
	end	

	private
  	def customer_params
    	params.require(:customer).permit(:name, :birthday)
  	end

end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController

  def create
    @customer = Customer.find(params[:customer_id])
    @reservation = @customer.reservations.create(reservation_params)
    redirect_to customer_path(@customer)
  end

  def destroy
    @customer = Customer.find(params[:customer_id])
    @reservation = @customer.reservations.find(params[:id])
    @reservation.destroy
    redirect_to customer_path(@customer)
  end
 
  private
    def reservation_params
      params.require(:reservation).permit(:product, :reservation_number)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/reservation_helper.rb
module ReservationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/customers/_form.html.erb
<%= form_with model: @customer, local: true do |form| %>

  <% if @customer.errors.any? %>
    <div id="error_explanation">
      <h2>
        Fehler verhinderten das hinzufügen eines neuen Kunden
      </h2>
      <ul>
        <% @customer.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :Name %><br>
    <%= form.text_field :name %>
  </p>
 
  <p>
    <%= form.label :Geburtstag %><br>
    <%= form.text_field :birthday %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/customers/edit.html.erb
<h1>Kunde bearbeiten</h1>

<%= render 'form' %>

<%= link_to 'Zurück', customers_path %>

app/views/customers/index.html.erb
<h1>Kunden</h1>
 
<%= link_to 'Neuer Kunde', new_customer_path %>

<table>
  <tr>
    <th>Name</th>
    <th>Geburtsdatum</th>
    <th></th>
  </tr>
 
 <% @customers.each do |customer| %>
    <tr>
      <td><%= customer.name %></td>
      <td><%= customer.birthday %></td>
      <td><%= link_to 'Anzeigen', customer_path(customer) %>
      <td><%= link_to 'Bearbeiten', edit_customer_path(customer) %></td>
      <td><%= link_to 'Löschen', customer_path(customer),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
</table>

app/views/customers/new.html.erb
<h1>Neuer Kunde</h1>

<%= render 'form' %>

<%= link_to 'Zurück', customers_path %>

app/views/customers/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @customer.name %>
</p>
 
<p>
  <strong>Geburtsdatum:</strong>
  <%= @customer.birthday %>
</p>

<h2>Reservierungen</h2>

<% @customer.reservations.each do |reservations| %>
  <p>
    <strong>Produkt:</strong>
    <%= reservations.product %>
  </p>
 
  <p>
    <strong>Reservierungsnummer:</strong>
    <%= reservations.reservation_number %>
  </p>

  <p>
  <%= link_to 'Reservierung löschen', [reservations.customer, reservations],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>

<% end %>
 
<h2>Neue Reservierung:</h2>
<%= form_with(model: [ @customer, @customer.reservations.build ], local: true) do |form| %>
  <p>
    <%= form.label :Produkt %><br>
    <%= form.text_field :product %>
  </p>
  <p>
    <%= form.label :Reservierungsnummer %><br>
    <%= form.text_area :reservation_number %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

<%= link_to 'Bearbeiten', edit_customer_path(@customer) %> │
<%= link_to 'Zurück', customers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>A3</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/reservation/_form.html.erb
<%= form_with(model: [ @customer, @customer.reservations.build ], local: true) do |form| %>
  <p>
    <%= form.label :Produkt %><br>
    <%= form.text_field :product %>
  </p>
  <p>
    <%= form.label :Reservierungsnummer %><br>
    <%= form.text_area :reservation_number %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/reservation/_reservation.html.erb
<p>
  <strong>Produkt:</strong>
  <%= reservations.product %>
</p>
 
<p>
  <strong>Reservationsnummer:</strong>
  <%= reservations.reservation_number %>
</p>

app/views/welcome/index.html.erb
<h1>Willkommen</h1>
<p>Information zu Kunden und Bestellungen</p>
<%= link_to 'Kunden', controller: 'customers' %>